from django.urls import path
from . import views

urlpatterns = [
    
    path('dashboard/', views.dashboard,name="dashboard"),
    path('public_login/', views.public_login,name="public_login"),
    path('logout/', views.logout,name="logout"),
    path('', views.police_login,name="police_login"),
    path('police_dashboard/', views.police_dashboard,name="police_dashboard"),
    path('police_logout/', views.police_logout,name="police_logout"),
    path('add_details/', views.add_details,name="add_details"),
    path('case_type/', views.case_type,name="case_type"),
    path('all_cases/', views.all_cases,name="all_cases"),
    path('public_register/', views.public_register,name="public_register"),
    path('all_detail/<int:pk>/', views.all_detail,name="all_detail"),
    path('choose_lawyer/', views.choose_lawyer,name="choose_lawyer"),
    path('requested_list/', views.requested_list,name="requested_list"),
    path('send_request/<int:pk>/', views.send_request,name="send_request"),
    path('lawyer_dashboard/', views.lawyer_dashboard,name="lawyer_dashboard"),
    path('lawyer_login/', views.lawyer_login,name="lawyer_login"),
    path('lawyer_logout/', views.lawyer_logout,name="lawyer_logout"),
    path('accept/<int:pk>/', views.accept,name="accept"),
    path('user_case/', views.user_case,name="user_case"),
    path('reject/<int:pk>/', views.reject,name="reject"),
    path('lawyer_doc/', views.lawyer_doc,name="lawyer_doc"),
    path('case_list/<int:pk>/', views.case_list,name="case_list"),
    path('all_case_detail/', views.all_case_detail,name="all_case_detail"),
    path('judge_dashboard/', views.judge_dashboard,name="judge_dashboard"),
    path('judge/', views.judge,name="judge"),
    path('judge_logout/', views.judge_logout,name="judge_logout"),
    path('case_list_judge/<int:pk>/', views.case_list_judge,name="case_list_judge"),
    path('all_case_list_detail/', views.all_case_list_detail,name="all_case_list_detail"),
    path('choose_lawyer_police/', views.choose_lawyer_police,name="choose_lawyer_police"),
    path('more_evidance/', views.more_evidance,name="more_evidance"),
    path('send_lawyer/<int:pk>/', views.send_lawyer,name="send_lawyer"),
    path('search_date/', views.search_date,name="search_date"),
    path('unsolved_cases/', views.unsolved_cases,name="unsolved_cases"),
    path('solved_cases/', views.solved_cases,name="solved_cases"),
    path('accept_police/<int:pk>/', views.accept_police,name="accept_police"),
    path('reject_police/<int:pk>/', views.reject_police,name="reject_police"),
    path('search_by_law/', views.search_by_law,name="search_by_law"),
    path('judge_solved/', views.judge_solved,name="judge_solved"),
    path('judge_unsolved/', views.judge_unsolved,name="judge_unsolved"),
    path('search_by_judge/', views.search_by_judge,name="search_by_judge"),
    path('judgement/<int:pk>/', views.judgement,name="judgement"),
    path('view_judgement/<int:pk>/', views.view_judgement,name="view_judgement"),

]
