# Generated by Django 3.2 on 2024-11-27 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Police_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=100)),
                ('station_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=200)),
                ('image', models.FileField(null=True, upload_to='documents/', verbose_name='Upload Image')),
            ],
        ),
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=200)),
                ('image', models.FileField(null=True, upload_to='documents/', verbose_name='Upload Image')),
                ('user_type', models.CharField(choices=[('', 'Select'), ('Victim', 'Victim'), ('Suspect', 'Suspect')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fir_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=100, null=True)),
                ('case_type', models.CharField(max_length=100, null=True)),
                ('victim_name', models.CharField(max_length=100)),
                ('suspect_name', models.CharField(max_length=15)),
                ('victim_gender', models.CharField(max_length=100)),
                ('case_date', models.DateField()),
                ('case_filed_date', models.DateField()),
                ('case_location', models.CharField(max_length=100)),
                ('victim_address', models.TextField(max_length=1000)),
                ('suspect_address', models.TextField(max_length=1000)),
                ('fir_doc', models.FileField(null=True, upload_to='documents/', verbose_name='FIR Document ')),
                ('evidance', models.FileField(null=True, upload_to='documents/', verbose_name='Evidance Document')),
                ('victim_photo', models.FileField(null=True, upload_to='documents/', verbose_name='Victim Photo ')),
                ('suspect_photo', models.FileField(null=True, upload_to='documents/', verbose_name='Suspect Photo ')),
                ('case_summary', models.TextField(max_length=1000)),
                ('police_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.police_detail')),
            ],
        ),
    ]
