# Generated by Django 3.2 on 2024-11-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyer_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=200)),
                ('image', models.FileField(null=True, upload_to='documents/', verbose_name='Upload Image')),
            ],
        ),
    ]
