# Generated by Django 3.2 on 2024-11-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lawyer_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user_detail',
            name='user_type',
        ),
    ]
