# Generated by Django 3.2 on 2024-11-27 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lawyer_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer_Evidance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=100)),
                ('lawyer_evidance_doc', models.FileField(upload_to='documents/', verbose_name='Evidance Document ')),
                ('other_doc', models.FileField(upload_to='documents/', verbose_name='Other Document ')),
                ('case_summary', models.TextField(max_length=2000)),
                ('lawyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lawyer_detail')),
            ],
        ),
    ]
