# Generated by Django 3.2 on 2024-12-22 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_judge_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fir_detail')),
                ('lawyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lawyer_detail')),
                ('police_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.police_detail')),
            ],
        ),
        migrations.CreateModel(
            name='More_Evidance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more_evidance_doc', models.FileField(upload_to='documents/', verbose_name='Evidance Document ')),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fir_detail')),
                ('lawyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lawyer_detail')),
            ],
        ),
    ]
