# Generated by Django 3.2 on 2024-12-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20241222_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='more_evidance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='send_case',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
