# Generated by Django 3.2 on 2024-12-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20241222_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir_detail',
            name='case_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
