# Generated by Django 3.2 on 2024-12-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_fir_detail_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_case',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
