# Generated by Django 3.2 on 2024-12-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_send_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir_detail',
            name='judgement',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
